[connections.postgresql]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "streamLitTest"
username = "postgres"
password = "1q2w3e"

[snowflake]
dialect = "snowflake"
host = "localhost"
port = "5432"
database = "TEST_STREAMLIT"
user = "ANDREI123222"
password = "Deidei1234"
account = "pxxqyjp-edb57287"
schema = "TEST_SCHEMA"